version: '3.4'
volumes:
  db-data:
  
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - db-data:/var/opt/mssql/data
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Pa55w0rd2019"
        MSSQL_PID: Express
    ports:
        - "1433:1433"
  smtp-server:
    container_name: smtp-server
    image: mailhog/mailhog:latest
    restart: always
    logging:
     driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - ./test/azurite:/data

  admin:
    container_name: admin
    depends_on:
        - sql-server-db
        - smtp-server
        - azurite
    build:
      context: .
      dockerfile: Admin/Dockerfile
    ports:
        - "8080:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Developement
        - MailHostUrl=smtp-server
        - MailPort=1025
        - DatabaseConnections__EmailDb=Server=sql-server-db,1433;Initial Catalog=Email;User ID =SA;Password=Pa55w0rd2019;TrustServerCertificate=true;

  api:
    container_name: api
    depends_on:
        - sql-server-db
        - smtp-server
        - azurite
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
        - "8010:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Developement
        - MailHostUrl=smtp-server
        - MailPort=1025
        - DatabaseConnections__EmailDb=Server=sql-server-db,1433;Initial Catalog=Email;User ID =SA;Password=Pa55w0rd2019;TrustServerCertificate=true;